# Generated by Django 4.0.4 on 2022-05-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.RenameField(
            model_name='juego',
            old_name='reseña',
            new_name='resena',
        ),
        migrations.AlterField(
            model_name='donador',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
